class CashMovement {
    static _repository = new CashMovementRepository();

    /**
     * Create cash movement record
     * CRITICAL: Always inserts as NEW row, never uses INSERT OR REPLACE
     * ID is auto-generated by IndexedDB auto-increment
     * 
     * @param {Object} data - Movesment data (MUST NOT include id field)
     * @param {number} data.cashRegisterId - Cash register ID
     * @param {string} data.type - Movement type ('in' or 'out')
     * @param {number} data.amount - Movement amount (positive number)
     * @param {string} data.reason - Movement reason/description
     * @param {number} [data.paymentId] - Optional: Payment ID that created this movement
     * @param {number} [data.expenseId] - Optional: Expense ID that created this movement
     * @param {number} [data.saleId] - Optional: Sale ID that created this movement
     * @returns {Promise<number>} - Auto-generated Movement ID
     */
    static async create(data) {
        const amount = parseFloat(data.amount);
        
        if (!data.cashRegisterId) {
            throw new Error('Cash movement debe tener un cashRegisterId asociado');
        }
        
        if (data.type !== 'in' && data.type !== 'out') {
            throw new Error('Tipo de movimiento debe ser "in" o "out"');
        }
        
        if (!amount || amount <= 0) {
            throw new Error('Monto debe ser un número positivo');
        }
        
        // CRITICAL: Build movement object WITHOUT id field
        // ID will be auto-generated by IndexedDB auto-increment
        const movement = {
            cashRegisterId: data.cashRegisterId,
            type: data.type,
            amount: amount,
            reason: data.reason || '',
            date: new Date().toISOString()
        };
        
        // FIX: Add reference fields if provided (for better CashMovement lookup)
        if (data.paymentId !== undefined && data.paymentId !== null) {
            movement.paymentId = data.paymentId;
        }
        if (data.expenseId !== undefined && data.expenseId !== null) {
            movement.expenseId = data.expenseId;
        }
        if (data.saleId !== undefined && data.saleId !== null) {
            movement.saleId = data.saleId;
        }
        
        // CRITICAL: Ensure movement object does NOT have id field
        if (movement.id !== undefined) {
            delete movement.id;
        }
        
        // CRITICAL: Use repository.create() which uses db.add()
        // db.add() ALWAYS inserts as new row (never replaces)
        // Auto-increment ensures unique ID generation (never reused)
        return await this._repository.create(movement);
    }

    static async getAll() {
        return await this._repository.findAll();
    }

    static async getByCashRegister(cashRegisterId) {
        return await this._repository.findByCashRegisterId(cashRegisterId);
    }

    static async getByType(type) {
        return await this._repository.findByType(type);
    }

    static async getByDateRange(startDate, endDate) {
        return await this._repository.findByDateRange(startDate, endDate);
    }

    /**
     * Get movements by payment ID
     * FIX: Added for better CashMovement lookup
     * @param {number} paymentId - Payment ID
     * @returns {Promise<Array>}
     */
    static async getByPaymentId(paymentId) {
        return await this._repository.findByPaymentId(paymentId);
    }

    /**
     * Get movements by expense ID
     * FIX: Added for better CashMovement lookup
     * @param {number} expenseId - Expense ID
     * @returns {Promise<Array>}
     */
    static async getByExpenseId(expenseId) {
        return await this._repository.findByExpenseId(expenseId);
    }

    /**
     * Get movements by sale ID
     * FIX: Added for better CashMovement lookup
     * @param {number} saleId - Sale ID
     * @returns {Promise<Array>}
     */
    static async getBySaleId(saleId) {
        return await this._repository.findBySaleId(saleId);
    }

    static async update(id, data) {
        return await this._repository.update(id, data);
    }

    static async delete(id) {
        return await this._repository.delete(id);
    }
}
