class Payment {
    static _repository = new PaymentRepository();

    /**
     * Create payment record (internal method - use PaymentService.registerPayment() instead)
     * CRITICAL: Always inserts as NEW row, never uses INSERT OR REPLACE
     * ID is auto-generated by IndexedDB auto-increment
     * 
     * @param {Object} payment - Payment object (MUST NOT include id field)
     * @returns {Promise<number>} - Auto-generated Payment ID
     */
    static async createPaymentRecord(payment) {
        // CRITICAL: Ensure payment object does NOT have id field
        // BaseRepository.create() will remove it, but we ensure it here too
        if (payment.id !== undefined) {
            console.warn('⚠️ Warning: Attempted to create payment with explicit id. ID removed - will use auto-increment.');
            delete payment.id;
        }
        
        // CRITICAL: Use repository.create() which uses db.add()
        // db.add() ALWAYS inserts as new row (never replaces)
        // Auto-increment ensures unique ID generation (never reused)
        return await this._repository.create(payment);
    }

    /**
     * Create payment using PaymentService (recommended)
     * @param {Object} data - Payment data
     * @returns {Promise<number>} - Payment ID
     */
    static async create(data) {
        return await PaymentService.registerPayment(data);
    }

    static async getBySale(saleId) {
        return await this._repository.findBySaleId(saleId);
    }

    static async getByCustomer(customerId) {
        return await this._repository.findByCustomerId(customerId);
    }

    static async getAll() {
        return await this._repository.findAll();
    }

    static async getByCashRegister(cashRegisterId) {
        return await this._repository.findByCashRegisterId(cashRegisterId);
    }

    static async delete(id) {
        return await this._repository.delete(id);
    }
}
