class StockMovement {
    static _repository = new StockMovementRepository();

    /**
     * Create stock movement record
     * CRITICAL: Always inserts as NEW row, never uses INSERT OR REPLACE
     * ID is auto-generated by IndexedDB auto-increment
     * 
     * @param {Object} data - Movement data (MUST NOT include id field)
     * @returns {Promise<number>} - Auto-generated Movement ID
     */
    static async create(data) {
        const product = await Product.getById(data.productId);
        const quantity = parseFloat(data.quantity);
        
        // CRITICAL: Build movement object WITHOUT id field
        // ID will be auto-generated by IndexedDB auto-increment
        const movement = {
            productId: data.productId,
            type: data.type,
            quantity: quantity,
            reference: data.reference || null,
            date: new Date().toISOString(),
            reason: data.reason || '',
            cost_value: product ? (Math.abs(quantity) * product.cost) : 0,
            sale_value: product ? (Math.abs(quantity) * product.price) : 0
        };
        
        // CRITICAL: Ensure movement object does NOT have id field
        if (movement.id !== undefined) {
            delete movement.id;
        }
        
        // CRITICAL: Use repository.create() which uses db.add()
        // db.add() ALWAYS inserts as new row (never replaces)
        // Auto-increment ensures unique ID generation (never reused)
        return await this._repository.create(movement);
    }

    static async getAll() {
        return await this._repository.findAll();
    }

    static async getByProduct(productId) {
        return await this._repository.findByProductId(productId);
    }

    static async getByType(type) {
        return await this._repository.findByType(type);
    }

    static async getByDateRange(startDate, endDate) {
        return await this._repository.findByDateRange(startDate, endDate);
    }

    /**
     * Create adjustment (use StockService instead)
     * @deprecated Use StockService.createAdjustment() instead
     */
    static async createAdjustment(productId, quantity, reason) {
        return await StockService.createAdjustment(productId, quantity, reason);
    }

    /**
     * Create loss (use StockService instead)
     * @deprecated Use StockService.createLoss() instead
     */
    static async createLoss(productId, quantity, reason) {
        return await StockService.createLoss(productId, quantity, reason);
    }

    /**
     * Create consumption (use StockService instead)
     * @deprecated Use StockService.createConsumption() instead
     */
    static async createConsumption(productId, quantity, reason) {
        return await StockService.createConsumption(productId, quantity, reason);
    }
}
