/**
 * Payment Service
 * Centralizes all payment-related business logic
 */
class PaymentService {
    /**
     * Validate payment amount (uses PaymentValidator)
     * @param {number} amount - Payment amount
     * @param {Object} sale - Sale object
     * @returns {Object} - { valid: boolean, error?: string, remaining?: number }
     */
    static validatePaymentAmount(amount, sale) {
        const validation = PaymentValidator.validateAmount(amount, sale);
        if (!validation.valid) {
            return validation;
        }

        // Calculate remaining for return value
        const saleTotal = parseFloat(sale.total) || 0;
        const salePaidAmount = parseFloat(sale.paidAmount) || 0;
        const remaining = saleTotal - salePaidAmount;

        return {
            valid: true,
            remaining: remaining
        };
    }

    /**
     * Validate payment method (uses PaymentValidator)
     * @param {string} method - Payment method
     * @returns {boolean}
     */
    static validatePaymentMethod(method) {
        const validation = PaymentValidator.validateMethod(method);
        return validation.valid;
    }

    /**
     * Calculate remaining debt for a sale
     * @param {Object} sale - Sale object
     * @returns {number}
     */
    static calculateRemainingDebt(sale) {
        const total = parseFloat(sale.total) || 0;
        const paid = parseFloat(sale.paidAmount) || 0;
        return Math.max(0, total - paid);
    }

    /**
     * Register a payment for a sale
     * CRITICAL: Uses atomic transaction - Payment and Sale update succeed or fail together
     * If any operation fails, entire transaction is rolled back automatically
     * Ensures sales and customer balance remain consistent
     * 
     * @param {Object} paymentData - Payment data
     * @returns {Promise<number>} - Payment ID
     */
    static async registerPayment(paymentData) {
        // ============================================
        // PHASE 1: VALIDATION (Read-only, outside transaction)
        // ============================================

        // Validate required fields
        if (!paymentData || !paymentData.saleId) {
            throw new Error('Payment debe tener un saleId asociado');
        }

        // Get sale (read-only, outside transaction)
        // Store original values for consistency check
        const sale = await Sale.getById(paymentData.saleId);
        if (!sale) {
            throw new Error(`No se encontró la venta #${paymentData.saleId} para registrar el pago`);
        }

        // Store original sale state for optimistic locking
        const originalSaleState = {
            id: sale.id,
            paidAmount: parseFloat(sale.paidAmount) || 0,
            total: parseFloat(sale.total) || 0,
            status: sale.status,
            updatedAt: sale.updatedAt
        };

        // Validate payment amount
        const validation = this.validatePaymentAmount(paymentData.amount, sale);
        if (!validation.valid) {
            throw new Error(validation.error);
        }

        // Validate payment method
        const paymentMethod = paymentData.paymentMethod || 'cash';
        if (!this.validatePaymentMethod(paymentMethod)) {
            throw new Error('Método de pago inválido');
        }

        // CRITICAL: Get open cash register - payments are ONLY allowed when cash register is OPEN
        const openCashRegister = await CashRegister.getOpen();
        if (!openCashRegister) {
            throw new Error('No se puede registrar un pago: La caja debe estar abierta. Por favor, abre la caja antes de registrar pagos de clientes.');
        }

        // ============================================
        // PHASE 2: PREPARE DATA (Read-only calculations)
        // ============================================

        // CRITICAL: Build payment object WITHOUT id field
        // ID will be auto-generated by IndexedDB auto-increment
        const payment = {
            saleId: paymentData.saleId,
            customerId: paymentData.customerId || sale.customerId || null,
            amount: parseFloat(paymentData.amount),
            paymentMethod: paymentMethod,
            date: new Date().toISOString(),
            notes: paymentData.notes || '',
            cashRegisterId: openCashRegister.id // CRITICAL: Always set - validated above that cash register is open
        };

        // CRITICAL: Ensure payment object does NOT have id field
        if (payment.id !== undefined) {
            delete payment.id;
        }

        // Calculate updated sale values BEFORE transaction
        const paymentAmount = parseFloat(paymentData.amount);
        const originalPaidAmount = originalSaleState.paidAmount;
        const originalTotal = originalSaleState.total;
        const newPaidAmount = Math.min(originalPaidAmount + paymentAmount, originalTotal);
        const isFullyPaid = newPaidAmount >= originalTotal;
        const hasPartialPayment = newPaidAmount > 0 && newPaidAmount < originalTotal;

        // Determine status: paid (completed), partial, or pending
        let newStatus = originalSaleState.status;
        if (isFullyPaid) {
            newStatus = 'completed'; // Fully paid
        } else if (hasPartialPayment) {
            newStatus = 'partial'; // Partially paid
        } else {
            newStatus = 'pending'; // No payment yet
        }

        // Prepare updated sale object
        const updatedSale = {
            ...sale,
            paidAmount: isFullyPaid ? originalTotal : newPaidAmount,
            status: newStatus,
            updatedAt: new Date().toISOString()
        };

        // ============================================
        // PHASE 3: ATOMIC TRANSACTION
        // All write operations must succeed or all fail
        // ============================================

        // SQLite mode supports atomic backend transaction
        if (db.mode === 'sqlite') {
            const result = await ApiClient.post('complex/payment', { payment });
            if (!result.success) throw new Error(result.error || 'Error al registrar pago en SQLite');
            return result.id;
        }

        try {
            // CRITICAL: Execute both operations in a single atomic transaction
            // IndexedDB automatically rolls back if any operation fails
            const paymentId = await new Promise((resolve, reject) => {
                const tx = db.db.transaction(['payments', 'sales'], 'readwrite');

                // Transaction error handler - automatic rollback
                tx.onerror = () => {
                    console.error('Payment transaction error:', tx.error);
                    reject(new Error(`Transaction failed: ${tx.error?.message || 'Unknown error'}`));
                };

                // Transaction abort handler - explicit rollback
                tx.onabort = () => {
                    console.error('Payment transaction aborted - all operations rolled back');
                    reject(new Error('Transaction aborted - all operations rolled back'));
                };

                const paymentStore = tx.objectStore('payments');
                const saleStore = tx.objectStore('sales');

                // Step 1: Verify sale hasn't changed (optimistic locking)
                // Read sale within transaction to ensure consistency
                const saleGetRequest = saleStore.get(sale.id);

                saleGetRequest.onsuccess = () => {
                    const currentSale = saleGetRequest.result;

                    // CRITICAL: Verify sale hasn't been modified by another transaction
                    if (!currentSale) {
                        tx.abort();
                        reject(new Error('Error: La venta fue eliminada durante el proceso'));
                        return;
                    }

                    // Verify paidAmount hasn't changed (consistency check)
                    const currentPaidAmount = parseFloat(currentSale.paidAmount) || 0;
                    if (Math.abs(currentPaidAmount - originalPaidAmount) > 0.01) {
                        tx.abort();
                        reject(new Error('🛑 La cuenta fue modificada por otra caja o ventana recientemente. Cierra esta ventana, actualiza la página y vuelve a intentarlo.'));
                        return;
                    }

                    // Step 2: Create payment record
                    const paymentRequest = paymentStore.add(payment);

                    paymentRequest.onsuccess = () => {
                        const pId = paymentRequest.result;

                        // Validate payment ID was generated
                        if (!pId || typeof pId !== 'number') {
                            tx.abort();
                            reject(new Error('Error: No se pudo obtener un ID válido para el pago'));
                            return;
                        }

                        // Step 3: Update sale within same transaction
                        const saleRequest = saleStore.put(updatedSale);

                        saleRequest.onsuccess = () => {
                            // CRITICAL: All operations succeeded - transaction will commit
                            // Both Payment and Sale are now consistent
                            resolve(pId);
                        };

                        saleRequest.onerror = () => {
                            // Sale update failed - abort entire transaction
                            tx.abort();
                            reject(new Error(`Error al actualizar la venta: ${saleRequest.error?.message || 'Unknown error'}`));
                        };
                    };

                    paymentRequest.onerror = () => {
                        // Payment creation failed - abort entire transaction
                        tx.abort();
                        reject(new Error(`Error al crear el pago: ${paymentRequest.error?.message || 'Unknown error'}`));
                    };
                };

                saleGetRequest.onerror = () => {
                    // Sale read failed - abort transaction
                    tx.abort();
                    reject(new Error(`Error al verificar la venta: ${saleGetRequest.error?.message || 'Unknown error'}`));
                };
            });

            // CRITICAL: Transaction completed successfully
            // Both Payment and Sale were updated atomically
            // Sales and customer balance remain consistent
            // If transaction failed, both operations were automatically rolled back

            return paymentId;
        } catch (error) {
            // CRITICAL: Transaction failed - all operations automatically rolled back
            // No partial state exists - database remains consistent
            console.error('CRITICAL: Payment transaction failed - all operations rolled back:', error);
            throw new Error(`Error al registrar el pago (operación revertida): ${error.message}`);
        }
    }

    /**
     * Calculate total debt from multiple sales
     * @param {Array} sales - Array of sale objects
     * @returns {number}
     */
    static calculateTotalDebt(sales) {
        return sales.reduce((sum, sale) => {
            const remaining = this.calculateRemainingDebt(sale);
            return sum + remaining;
        }, 0);
    }
}
