/**
 * Sale Service
 * Centralizes sale creation and business logic
 */
class SaleService {
    /**
     * Generate next sale number
     * @returns {Promise<number>}
     */
    static async generateSaleNumber() {
        const lastSale = await Sale.getLastSale();
        return lastSale ? lastSale.saleNumber + 1 : 1;
    }

    /**
     * Validate sale data before creation (uses SaleValidator)
     * @param {Object} saleData - Sale data
     * @returns {Object} - { valid: boolean, error?: string }
     */
    static validateSaleData(saleData) {
        return SaleValidator.validate(saleData);
    }

    /**
     * Create a sale with all business logic
     * @param {Object} saleData - Sale data
     * @returns {Promise<number>} - Sale ID
     */
    static async createSale(saleData) {
        // Idempotency: if key present and sale already exists, return existing (no new sale, no stock deduction)
        const idempotencyKey = saleData.idempotencyKey != null && String(saleData.idempotencyKey).trim() !== ''
            ? String(saleData.idempotencyKey).trim()
            : null;
        if (idempotencyKey) {
            const existing = await Sale.findByIdempotencyKey(idempotencyKey);
            if (existing) {
                return { saleId: existing.id, fromIdempotency: true };
            }
        }

        // Validate sale data
        const validation = this.validateSaleData(saleData);
        if (!validation.valid) {
            throw new Error(validation.error);
        }

        // Generate sale number
        const saleNumber = await this.generateSaleNumber();

        // Ensure customerId is set for pending sales
        const isPending = saleData.status === 'pending' || saleData.status === 'partial';

        // CRITICAL: Credit sales MUST have customerId - validate this
        if (isPending && !saleData.customerId) {
            throw new Error('Las ventas a crédito (fiadas) deben tener un cliente asociado');
        }

        // Límite de crédito: si el cliente tiene límite, deuda actual + total de esta venta no puede superarlo
        if (isPending && saleData.customerId) {
            const customer = await Customer.getById(saleData.customerId);
            if (customer && customer.creditLimit != null && !isNaN(parseFloat(customer.creditLimit))) {
                const limit = parseFloat(customer.creditLimit);
                const balance = await AccountService.getCustomerBalance(saleData.customerId);
                const newTotalDebt = (balance.totalDebt || 0) + (parseFloat(saleData.total) || 0);
                if (newTotalDebt > limit) {
                    throw new Error(
                        `Límite de crédito superado. Deuda actual: ${formatCLP(balance.totalDebt || 0)}, ` +
                        `esta venta: ${formatCLP(saleData.total)}, total: ${formatCLP(newTotalDebt)}. Límite del cliente: ${formatCLP(limit)}.`
                    );
                }
            }
        }

        // CRITICAL: Build sale object WITHOUT id field
        // ID will be auto-generated by IndexedDB auto-increment
        // This ensures each sale is a NEW unique record
        const sale = {
            saleNumber: saleNumber,
            date: new Date().toISOString(),
            // CRITICAL: For credit sales, customerId MUST be set (never null)
            // For completed sales, customerId can be null (walk-in customers)
            customerId: isPending ? saleData.customerId : (saleData.customerId || null),
            items: Array.isArray(saleData.items) ? saleData.items : [],
            subtotal: parseFloat(saleData.subtotal) || 0,
            total: parseFloat(saleData.total) || 0,
            paymentMethod: saleData.paymentMethod || 'cash',
            paymentDetails: saleData.paymentDetails || null,
            cashRegisterId: saleData.cashRegisterId,
            status: saleData.status || 'completed',
            paidAmount: saleData.paidAmount !== undefined && !isNaN(parseFloat(saleData.paidAmount)) ? parseFloat(saleData.paidAmount) : (isPending ? 0 : parseFloat(saleData.total) || 0),

            // Notebook Features: Desglose Fiscal
            ...Sale.computeFiscalFromTotal(parseFloat(saleData.total) || 0),

            // B6: Campos de auditoría
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            // C3: Trazabilidad — quién creó/modificó
            createdBy: AuditLogService.getCurrentUserId(),
            updatedBy: AuditLogService.getCurrentUserId()
        };
        if (idempotencyKey) {
            sale.idempotencyKey = idempotencyKey;
        }

        // CRITICAL: Ensure sale object does NOT have id field
        if (sale.id !== undefined) {
            delete sale.id;
        }

        // Pre-validate stock availability (outside transaction for clear error messages)
        const validItems = [];
        for (const item of sale.items) {
            if (!item || !item.productId || item.quantity === undefined) continue;
            const qty = parseFloat(item.quantity) || 0;
            if (qty <= 0) continue;
            const product = await Product.getById(item.productId);
            const validation = ProductValidator.validateStock(product, qty);
            if (!validation.valid) {
                throw new Error(validation.error);
            }
            validItems.push({ productId: item.productId, qty });
        }

        // CRITICAL FIX: Single atomic transaction - sale + product updates + stock movements
        let saleId;
        if (db.mode === 'sqlite') {
            const result = await ApiClient.post('complex/sale', { sale, validItems });
            if (!result.success) throw new Error(result.error || 'Error al crear venta en SQLite');
            saleId = result.id;
        } else {
            // Original IndexedDB Transaction
            saleId = await new Promise((resolve, reject) => {
                const tx = db.db.transaction(['sales', 'products', 'stockMovements'], 'readwrite');
                let resolvedSaleId = null;

                tx.onerror = () => {
                    reject(new Error(`Transacción fallida: ${tx.error?.message || 'Error desconocido'}`));
                };
                tx.onabort = () => {
                    reject(new Error('Transacción abortada: venta y stock se revirtieron'));
                };
                tx.oncomplete = () => {
                    resolve(resolvedSaleId);
                };

                const saleStore = tx.objectStore('sales');
                const productStore = tx.objectStore('products');
                const movementStore = tx.objectStore('stockMovements');

                const saleRequest = saleStore.add(sale);
                saleRequest.onsuccess = () => {
                    const id = saleRequest.result;
                    if (!id || typeof id !== 'number') {
                        tx.abort();
                        return;
                    }
                    resolvedSaleId = id;
                    for (const { productId, qty } of validItems) {
                        const getReq = productStore.get(productId);
                        getReq.onsuccess = () => {
                            const product = getReq.result;
                            if (!product) { tx.abort(); return; }
                            const currentStock = parseFloat(product.stock) || 0;
                            const newStock = currentStock - qty;
                            if (newStock < 0) { tx.abort(); return; }
                            productStore.put({
                                ...product,
                                stock: newStock,
                                lastSoldAt: new Date().toISOString(), // Notebook Feature: Track rotation
                                updatedAt: new Date().toISOString()
                            });
                            movementStore.add({
                                productId,
                                type: 'sale',
                                quantity: -qty,
                                reference: id,
                                date: new Date().toISOString(),
                                reason: '',
                                cost_value: (product.cost || 0) * qty,
                                sale_value: (product.price || 0) * qty
                            });
                        };
                    }
                };
                saleRequest.onerror = () => {
                    tx.abort();
                };
            });
        }

        // C2: Audit log (después de la transacción atómica exitosa)
        AuditLogService.log({
            entity: 'sale', entityId: saleId, action: 'create',
            summary: `Venta #${saleNumber} creada — Total: ${sale.total}, Estado: ${sale.status}`,
            metadata: {
                saleNumber,
                total: sale.total,
                status: sale.status,
                paymentMethod: sale.paymentMethod,
                customerId: sale.customerId,
                itemCount: sale.items.length
            }
        });

        return saleId;
    }

    /**
     * Calculate paid amount from payment details
     * @param {Object|null} paymentDetails - Payment details object
     * @param {number} defaultAmount - Default amount if no payment details
     * @returns {number}
     */
    static calculatePaidAmount(paymentDetails, defaultAmount = 0) {
        if (!paymentDetails) {
            return defaultAmount;
        }

        return Object.values(paymentDetails).reduce((sum, val) => sum + (parseFloat(val) || 0), 0);
    }

    /**
     * Delete a sale and restore stock
     */
    static async deleteSale(saleId) {
        const sale = await Sale.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        // Restore stock in an atomic transaction
        if (db.mode === 'sqlite') {
            const result = await ApiClient.delete(`complex/sale/${saleId}`);
            if (!result.success) throw new Error(result.error || 'Error al anular venta en SQLite');
            // Log auditing (after successful transaction)
            AuditLogService.log({
                entity: 'sale', entityId: saleId, action: 'delete',
                summary: `Venta #${sale.saleNumber} eliminada (SQLite). Stock devuelto.`,
                metadata: { total: sale.total, customerId: sale.customerId }
            });
            return true;
        }

        return new Promise((resolve, reject) => {
            const tx = db.db.transaction(['sales', 'products', 'stockMovements'], 'readwrite');

            tx.onerror = () => reject(new Error(`Error al anular venta: ${tx.error?.message}`));
            tx.oncomplete = () => {
                // Log auditing (after successful transaction)
                AuditLogService.log({
                    entity: 'sale', entityId: saleId, action: 'delete',
                    summary: `Venta #${sale.saleNumber} eliminada (Transacción Atómica). Stock devuelto.`,
                    metadata: { total: sale.total, customerId: sale.customerId }
                });
                resolve(true);
            };

            const saleStore = tx.objectStore('sales');
            const productStore = tx.objectStore('products');
            const movementStore = tx.objectStore('stockMovements');

            // 1. Marcar como eliminada o borrar
            saleStore.delete(saleId);

            // 2. Devolver stock e historial
            for (const item of sale.items) {
                if (!item.productId) continue;

                const getReq = productStore.get(item.productId);
                getReq.onsuccess = () => {
                    const product = getReq.result;
                    if (product) {
                        const qty = parseFloat(item.quantity) || 0;
                        const newStock = (parseFloat(product.stock) || 0) + qty;

                        productStore.put({
                            ...product,
                            stock: newStock,
                            updatedAt: new Date().toISOString()
                        });

                        movementStore.add({
                            productId: product.id,
                            type: 'adjustment',
                            quantity: qty,
                            reference: saleId,
                            date: new Date().toISOString(),
                            reason: `Anulación Venta #${sale.saleNumber}`
                        });
                    }
                };
            }
        });
    }
}
